#!/usr/bin/env node

const command = require('commander');
const fs = require('fs');
require('colors');

command
  .version('1.0.0')
  .description('Create TimeTracker log entries from your system log')
  .option('-w, --write', 'Actually write to TimeTracker - if not provided, preview is displayed');


let readerClass;
if (fs.existsSync('ttefsl-entries.txt')) {
  readerClass = require('./lib/reader/EntryFile');
} else if (process.platform === 'win32') {
  readerClass = require('./lib/reader/Windows');
} else if (process.platform === 'darwin') {
  throw new Error('MacOS is not supported (yet)');
} else {
  throw new Error('Linux is not supported (yet)');
}

const reader = new readerClass(command);

const AbstractLogger = require('./lib/logger/Abstract');
AbstractLogger.configureCommand(command);

command.parse(process.argv);

const Logger = command.write ? require('./lib/logger/TimeTracker') : require('./lib/logger/Preview');
const logger = new Logger(command);

logger.configure();
reader.configure();
reader.read().then((entries) => {
  logger.setEntries(entries);
  logger.flush();
});